### ISSUE TITLE
SQL issues with Sangar

### ISSUE THREAD

**Issue by brynjolf** [zlepper/TechnicSolderHelper#25]
Happened after deleting the SolderHelper folder and starting over on a directory on Wanderlust Reloaded. Most likely OpenComputers causing the issue.

```
SQL logic error or missing database
near "Sangar": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at TechnicSolderHelper.SQL.SqlHelper.ExecuteDatabaseQuery(String sql, Boolean async)
   at TechnicSolderHelper.SQL.OwnPermissionsSqlHelper.AddAuthor(String modId, String authorName)
   at TechnicSolderHelper.SolderHelper.GetAuthors(Mcmod mod)
   at TechnicSolderHelper.SolderHelper.CreateTechnicModZip(Mcmod mod, String modfile)
   at TechnicSolderHelper.SolderHelper.Start()
   at TechnicSolderHelper.SolderHelper.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TechnicSolderHelper.Program.Main()
```

**Comment by unseenline** [comment]
I can can confirm that there is an error when loading the WanderLust Reloaded mod pack from FTB
I'm attaching my error log as it has line numbers that should be of help.
```
SQL logic error or missing database
near "Sangar": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at TechnicSolderHelper.SQL.SqlHelper.ExecuteDatabaseQuery(String sql, Boolean async) in c:\GAMES\Minecraft\TechnicSolderHelperFork\TechnicSolderHelper\SQL\SQLhelper.cs:line 97
   at TechnicSolderHelper.SQL.OwnPermissionsSqlHelper.AddAuthor(String modId, String authorName) in c:\GAMES\Minecraft\TechnicSolderHelperFork\TechnicSolderHelper\SQL\OwnPermissionsSQLHelper.cs:line 142
   at TechnicSolderHelper.SolderHelper.GetAuthors(Mcmod mod) in c:\GAMES\Minecraft\TechnicSolderHelperFork\TechnicSolderHelper\TechnicSolderHelper.cs:line 119
   at TechnicSolderHelper.SolderHelper.CreateTechnicModZip(Mcmod mod, String modfile) in c:\GAMES\Minecraft\TechnicSolderHelperFork\TechnicSolderHelper\TechnicStuff.cs:line 369
   at TechnicSolderHelper.SolderHelper.Start() in c:\GAMES\Minecraft\TechnicSolderHelperFork\TechnicSolderHelper\TechnicSolderHelper.cs:line 472
   at TechnicSolderHelper.SolderHelper.button1_Click(Object sender, EventArgs e) in c:\GAMES\Minecraft\TechnicSolderHelperFork\TechnicSolderHelper\TechnicSolderHelper.cs:line 1320
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TechnicSolderHelper.Program.Main() in c:\GAMES\Minecraft\TechnicSolderHelperFork\TechnicSolderHelper\Program.cs:line 18
```

**Comment by unseenline** [comment]
I Have a fix for this, will create a pull request for it. It was because of the following line in mcmod.info. ' is reserved in SQL for strings and this broke the formatting at 'Sangar', and again at 'Lord Joda' .
```
"authorList": ["Florian 'Sangar' Nuecke", "Johannes 'Lord Joda' Lohrer", "Everyone who contributed to the mod on Github - thank you!"],
```
