### ISSUE TITLE
[Bug] "Corrupted" file/folder

### ISSUE THREAD

**Issue by aschmois** [zlepper/TechnicSolderHelper#61]
Hey, back again. Tried using the app once more and it fails to read the mod list. It tries to read one mod and it crashes with this error:

````
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The file or directory is corrupted and unreadable
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at TechnicSolderHelper.SolderHelper.Start()
   at TechnicSolderHelper.SolderHelper.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
TechnicSolderHelper
    Assembly Version: 1.0.5689.25151
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/andre/AppData/Local/Apps/2.0/2WWBB446.3BJ/LTCHMMQH.M92/tech..tion_0000000000000000_0001.0000_833dee209de738f4/TechnicSolderHelper.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/andre/AppData/Local/Apps/2.0/2WWBB446.3BJ/LTCHMMQH.M92/tech..tion_0000000000000000_0001.0000_833dee209de738f4/Newtonsoft.Json.DLL
----------------------------------------
System.IO.Abstractions
    Assembly Version: 2.0.0.115
    Win32 Version: 2.0.0.115
    CodeBase: file:///C:/Users/andre/AppData/Local/Apps/2.0/2WWBB446.3BJ/LTCHMMQH.M92/tech..tion_0000000000000000_0001.0000_833dee209de738f4/System.IO.Abstractions.DLL
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.96.0
    Win32 Version: 1.0.96.0
    CodeBase: file:///C:/Users/andre/AppData/Local/Apps/2.0/2WWBB446.3BJ/LTCHMMQH.M92/tech..tion_0000000000000000_0001.0000_833dee209de738f4/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Mono.Data.Sqlite
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Users/andre/AppData/Local/Apps/2.0/2WWBB446.3BJ/LTCHMMQH.M92/tech..tion_0000000000000000_0001.0000_833dee209de738f4/Mono.Data.Sqlite.DLL
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
MySql.Data
    Assembly Version: 6.9.6.0
    Win32 Version: 6.9.6.0
    CodeBase: file:///C:/Users/andre/AppData/Local/Apps/2.0/2WWBB446.3BJ/LTCHMMQH.M92/tech..tion_0000000000000000_0001.0000_833dee209de738f4/MySql.Data.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


````

Tried deleting the mod that it tried to load, but it just fails again on the next mod. These mods are definitely not corrupt. I am using the latest compiled version 1.0.7.7 and note! **I am using Windows 10**

Edit: .NET version is 4.6 (can't really change this part since it's now built into the OS)

Edit 2: Tried checking debug logging, but no log is ever generated (probably fails beforehand)

Edit 3: I tested on windows 8.1, issue persists.

**Comment by zlepper** [comment]
Please go into %appdata%\SolderHelper and delete the file "7za.exe" then try running SolderHelper again and the issue should be gone.

**Comment by aschmois** [comment]
Tried that a few times, also tried a different computer, it's weird... Working now, was it a broken 7z build?

**Comment by zlepper** [comment]
I recently switched cloud provider and didn't move the 7z file over to the
new place.
So i just had to upload the file.

2015-08-04 8:42 GMT+02:00 aschmois <notifications@github.com>:

**Comment by aschmois** [comment]
Alright, thanks, flawless execution now, thank you for a great product ; wish I wouldn't have been impatient though, I just spent a few hours manually uploading :weary:
