### ISSUE TITLE
HttpRequestException on load

### ISSUE THREAD

**Issue by skwerlman** [zlepper/TechnicSolderHelper#76]
I installed TSH today, but whenever I try to load it, it closes instantly.

After some digging, I found this in the .NET logs:
```
Application: TechnicSolderHelper.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Http.HttpRequestException

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResultCore(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Result()
   at TechnicSolderHelper.SQL.FtbPermissionsSqlHelper.LoadOnlinePermissions()
   at TechnicSolderHelper.SQL.FtbPermissionsSqlHelper.Load()
   at TechnicSolderHelper.SQL.FtbPermissionsSqlHelper..ctor()
   at TechnicSolderHelper.SolderHelper..ctor()
   at TechnicSolderHelper.Program.Main()
```

I am able to access http://ftb.cursecdn.com/FTB2/static/permissions/permissions.json, so it's not a network issue.

**Comment by zlepper** [comment]
That is not the site i'm querrying against, but i have had previous issues where the ftb site has been offline. 
And I can't reproduce the issue myself right now, so not much I can do. 

I also have a majorly overhauled version coming out soon, so that is where i'm directing most of my development effort right now.

**Comment by skwerlman** [comment]
It looks like it was a server side thing, though it'd be nice if it did something other than fail silently.

**Comment by zlepper** [comment]
Made it so it still fails silently, it however doesn't crash the entire program, just prevents it from reading permissions.

**Comment by skwerlman** [comment]
Thanks for the fix :smile:
